sudo: required
services: -docker
before_install:
  - docker build -t kdkdas8/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true kdkdas8/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-637423444029"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
